package com.joshgm3z.triplerocktv.util

fun String?.languageName(): String {
    if (isNullOrBlank()) return "Unknown"
    val normalized = trim().lowercase().replace('_', '-')
    return when (normalized) {
        "en" -> "English"
        "es" -> "Spanish"
        "fr" -> "French"
        "de" -> "German"
        "it" -> "Italian"
        "pt" -> "Portuguese"
        "pt-br" -> "Portuguese (Brazil)"
        "pt-pt" -> "Portuguese (Portugal)"
        "zh" -> "Chinese"
        "zh-cn" -> "Chinese (Simplified)"
        "zh-tw" -> "Chinese (Traditional)"
        "ja" -> "Japanese"
        "ko" -> "Korean"
        "ru" -> "Russian"
        "ar" -> "Arabic"
        "hi" -> "Hindi"
        "bn" -> "Bengali"
        "vi" -> "Vietnamese"
        "tr" -> "Turkish"
        "nl" -> "Dutch"
        "sv" -> "Swedish"
        "no" -> "Norwegian"
        "da" -> "Danish"
        "fi" -> "Finnish"
        "pl" -> "Polish"
        "cs" -> "Czech"
        "el" -> "Greek"
        "he" -> "Hebrew"
        "ro" -> "Romanian"
        "hu" -> "Hungarian"
        "uk" -> "Ukrainian"
        "sr" -> "Serbian"
        "hr" -> "Croatian"
        "sk" -> "Slovak"
        "sl" -> "Slovenian"
        "lt" -> "Lithuanian"
        "lv" -> "Latvian"
        "et" -> "Estonian"
        "ms" -> "Malay"
        "id" -> "Indonesian"
        "in" -> "Indonesian" // sometimes 'in' is used
        "th" -> "Thai"
        "fil", "tl" -> "Filipino"
        "fa" -> "Persian"
        "ur" -> "Urdu"
        "pa" -> "Punjabi"
        "gu" -> "Gujarati"
        "mr" -> "Marathi"
        "te" -> "Telugu"
        "kn" -> "Kannada"
        "ml" -> "Malayalam"
        "si" -> "Sinhala"
        else -> this
    }
}